const fs=require('fs');
const vm=require('vm');
const assert=require('node:assert/strict');
const root=require('path').resolve(__dirname, '..') + '/';
const nodes=new Map();
const element=()=>({value:'',textContent:'',dataset:{},setAttribute(){},setCustomValidity(message){this.validationMessage=message},querySelector(){return this.submitButton??=element()},reportValidity(){return false},handlers:{},addEventListener(name,fn){this.handlers[name]=fn},children:[],appendChild(child){this.children.push(child)},classList:{values:new Set(),contains(name){return this.values.has(name)},add(name){this.values.add(name)},remove(name){this.values.delete(name)}}});
const context=vm.createContext({window:{addEventListener(){}},document:{querySelector(s){if(!nodes.has(s))nodes.set(s,element());return nodes.get(s)},querySelectorAll(){return []},createElement:element},Intl,Date,Set,console});
vm.runInContext(fs.readFileSync(root+'pricing-data.js','utf8'),context);
let source=fs.readFileSync(root+'booking.js','utf8');
vm.runInContext(source.slice(0,source.lastIndexOf('\nupdateHelpTextDefault();')),context);
const run=code=>vm.runInContext(code,context);
run('availabilityLoaded=true; coverageStart="2026-09-11"; coverageEnd="2028-10-01";');
assert.equal(run("Object.keys(pricing.nightlyPrices).length"),24);
for(const [m,p] of Object.entries(context.window.lakeHousePricing.nightlyPrices)){
  const [y,n]=m.split('-').map(Number);assert.equal(p.length,new Date(y,n,0).getDate(),m);
}
const night=(date,g=1)=>run(`getNightPrice(parseDateKey('${date}'),${g})`);
const stay=(a,b,g)=>run(`getStayEstimate('${a}','${b}',${g})`);
assert.equal(night('2026-09-28').airbnbAmount,2626);
assert.equal(night('2026-10-20').airbnbAmount,2388);
assert.equal(night('2026-10-26').airbnbAmount,2827);
assert.equal(night('2026-10-30').airbnbAmount,2984);
assert.equal(night('2026-11-30').airbnbAmount,2388);
assert.equal(night('2026-12-01').airbnbAmount,2984);
assert.equal(night('2026-12-04').airbnbAmount,3223);
assert.equal(night('2027-02-19').airbnbAmount,3223);
assert.equal(night('2027-02-20').airbnbAmount,9000);
assert.equal(night('2027-02-23').airbnbAmount,9000);
assert.equal(night('2027-02-24').airbnbAmount,12900);
assert.equal(night('2027-02-27').airbnbAmount,14500);
assert.equal(night('2027-03-02').airbnbAmount,14500);
assert.equal(night('2027-03-03').airbnbAmount,12900);
assert.equal(night('2027-03-09').airbnbAmount,12900);
assert.equal(night('2027-03-10').airbnbAmount,2984);
assert.equal(night('2028-01-02').airbnbAmount,3581);
assert.equal(night('2028-02-29').airbnbAmount,2984);
assert.equal(night('2028-09-01'),null);
assert.equal(night('2026-10-05'),null);
assert.equal(night('2026-09-10'),null);
assert.equal(night('2026-12-01').amount,2685.6);
assert.equal(night('2026-12-01',6).amount,3761.1);
const short=stay('2026-09-28','2026-10-01',2);
assert.equal(short.total,8885.5);
assert.equal(short.cleaning,850);assert.equal(short.linen,300);
assert.equal(short.lengthDiscount,0);
const weekly=stay('2026-09-28','2026-10-05',2);
assert.equal(weekly.total,17394.55);
assert.equal(weekly.lengthDiscount,.1);
assert.equal(stay('2027-02-27','2027-03-03',6).total,58252);
assert.equal(stay('2027-04-01','2027-04-28',1).lengthDiscount,.1);
const monthly=stay('2027-04-01','2027-04-29',1);
assert.equal(monthly.lengthDiscount,.3);
assert.equal(monthly.total,54842.32); // (20*2984+8*3223)*0.7*0.9 + 850 + 150
assert.equal(stay('2026-10-04','2026-10-06',2),null);
assert.equal(stay('2028-08-31','2028-09-02',2),null);
assert.equal(stay('2027-03-27','2027-03-29',2).nights,2);
assert.equal(stay('2026-09-28','2026-09-28',2),null);
assert.equal(stay('2026-10-01','2026-09-28',2),null);
run('updateSummary(); renderCalendar();');
nodes.get('[data-check-in]').value='2026-09-28';nodes.get('[data-check-out]').value='2026-10-01';nodes.get('[data-guests]').value='2';
run('updateSummary();');assert.match(nodes.get('[data-price-estimate]').textContent,/8,885.5/);
run("bookedDates.add('2026-09-29'); updateSummary();");
assert.equal(nodes.get('[data-price-estimate]').textContent,'Dates unavailable');
run('bookedDates.clear();');nodes.get('[data-check-in]').value='2028-09-01';nodes.get('[data-check-out]').value='2028-09-05';run('updateSummary();');
assert.equal(nodes.get('[data-price-estimate]').textContent,'Price on request');
console.log('PASS: 24 months, date overrides, guest threshold, fees, weekly/monthly discounts, DST, unknown dates, availability and summary rendering.');

// Language switches must also change dynamic pricing text when a URL has ?lang=sv.
const i18nContext=vm.createContext({window:{location:{search:'?lang=sv'}},document:{addEventListener(){}},localStorage:{getItem(){return 'sv'}},URLSearchParams,console});
vm.runInContext(fs.readFileSync(root+'i18n.js','utf8'),i18nContext);
vm.runInContext("appliedLanguage='de';",i18nContext);
assert.equal(vm.runInContext('getCurrentLanguage()',i18nContext),'de');
assert.equal(vm.runInContext("t('Accommodation')",i18nContext),'Unterkunft');
console.log('PASS: dynamic pricing follows selected language.');

// Regression: booked and blocked dates must be equally unselectable, including checkout.
const actualAvailability=JSON.parse(fs.readFileSync(root+'availability.json','utf8'));
context.testAvailability=actualAvailability;
run('bookedDates=collectUnavailableDates(testAvailability); coverageStart=testAvailability.coverage_start; coverageEnd=testAvailability.coverage_end; availabilityLoaded=true; availabilityLoadFailed=false;');
for(let day=21;day<=27;day++)assert.equal(run(`isUnavailable(parseDateKey('2026-09-${day}'))`),true);
assert.equal(run("isUnavailable(parseDateKey('2026-09-28'))"),false);
assert.equal(run("collectUnavailableDates({booked_dates:['2026-09-21'],blocked_ranges:[{start:'2026-09-24',end:'2026-09-28'}]}).has('2026-09-27')"),true);
const checkIn=nodes.get('[data-check-in]'),checkOut=nodes.get('[data-check-out]');
checkIn.value='';checkOut.value='';
run("selectDate('2026-09-24')");assert.equal(checkIn.value,'');
run("selectDate('2026-09-28'); selectDate('2026-10-01');");
assert.equal(run('validateSelection()'),true);
checkIn.value='2026-10-04';checkOut.value='2026-10-05';assert.equal(run('validateSelection()'),false);
checkIn.value='2026-11-02';checkOut.value='';run("selectDate('2026-11-16')");assert.equal(checkOut.value,'');
checkIn.value='2026-09-21';checkOut.value='2026-09-28';
context.window.location={href:''};
nodes.get('[data-booking-request-form]').handlers.submit({preventDefault(){}});
assert.equal(context.window.location.href,'');
assert.match(checkIn.validationMessage,/unavailable/);
assert.equal(nodes.get('[data-booking-request-form]').submitButton.disabled,true);
checkIn.value='';checkOut.value='';
nodes.get('[data-calendar-grid]').children=[];
run('visibleMonth=new Date(2026,8,1);renderCalendar();');
for(let d=21;d<=27;d++){
const button=nodes.get('[data-calendar-grid]').children.find(e=>e.dataset.date===`2026-09-${d}`);
assert.equal(button.disabled,true);assert.equal(button.classList.contains('unavailable'),true);assert.match(button.innerHTML,/×/);
}
run('availabilityLoaded=false;');assert.equal(run('validateSelection()'),false);
run("selectDate('2026-09-28')");assert.equal(checkIn.value,'');
(async()=>{
context.fetch=async()=>({ok:false});await run('loadAvailability()');
assert.equal(run('availabilityLoadFailed'),true);assert.equal(run('validateSelection()'),false);
context.fetch=async()=>({ok:true,json:async()=>({...actualAvailability,updated_at:'2026-01-01T00:00:00Z'})});
await run('loadAvailability()');assert.equal(run('availabilityLoadFailed'),true);
context.fetch=async()=>({ok:true,json:async()=>({...actualAvailability,updated_at:new Date().toISOString()})});
await run('loadAvailability()');assert.equal(run('availabilityLoadFailed'),false);
assert.equal(run("isUnavailable(parseDateKey('2026-09-24'))"),true);
console.log('PASS: reserved/blocked dates, manual input, blocked checkout, crossing blocked ranges, disabled calendar cells, submit guard and failed/stale calendar loading.');
})().catch(e=>{console.error(e);process.exitCode=1});
